# Site settings
title: ThinkSpace
# the subpath baseurl must be to be publish & working in production under thinkspace.ch
# if you want to preview the website under liip.github.io/thinkspace, you have to change baseurl to /thinkspace
baseurl: ""
url: "http://thinkspace.ch" # the base hostname & protocol for your site
contact_email: "ludovic.turmel@liip.ch"
phone: +41 21 533 13 00
email: "hello@thinkspace.ch"
twitter_username: liip

# Build settings
markdown: kramdown
exclude: [node_modules]
